"""Veo backend: the shot generated by Google's video model, not drawn.

The drawn backends build a dog out of primitives, and a dog built out of
primitives looks like a dog built out of primitives. This one hands the shot
to Veo instead and gets photoreal footage back, which is the one way to have
the channel's own animal on screen without either filming it or sculpting it.

Two things make it usable for a channel rather than a toy:

  Reference images. Veo 3.1 takes up to three, and they lock the subject's
  identity across a generation. Point `visuals.veo.reference_images` at
  photographs of the actual dog and every shot is that dog, rather than a
  different plausible dog each time - which is exactly the failure the drawn
  renderer was built to avoid and the failure stock footage has by nature.

  A budget. Generation is billed per second of successful output, so a
  runaway build is a bill rather than a slow afternoon. `max_clips_per_build`
  caps how many clips one video may generate; past the cap the provider
  stands aside and the rest of `visuals.providers` handles the remaining
  shots.

Flow, Google's filmmaking UI, has no public API. It is the same models behind
a different door, so clips made by hand in Flow are dropped into
`workspace/<slug>/media/` as `000.mp4`, `001.mp4` and so on, and `fetch_clip`
reuses them on the next build. That route needs none of this module.
"""
from __future__ import annotations

import os
import shutil
import time
from pathlib import Path
from typing import Any

MODEL_DEFAULT = "veo-3.1-generate-preview"
POLL_SECONDS = 10
POLL_LIMIT = 60          # ten minutes; a clip that slow has gone wrong


def _client(settings: dict[str, Any]):
    """A Vertex AI client when a Cloud project is configured, else a Gemini one.

    The two are the same models billed through different doors. The Gemini
    API's free tier has no Veo quota at all, while a Google Cloud free-trial
    project pays for Vertex AI out of its trial credit - so Vertex is the
    route that costs nothing until that credit is spent. It authenticates
    with `gcloud auth application-default login`, not a key.
    """
    from google import genai

    vertex = settings.get("vertex") or {}
    project = vertex.get("project") or os.environ.get("GOOGLE_CLOUD_PROJECT", "")
    if project:
        return genai.Client(vertexai=True, project=project,
                            location=vertex.get("location") or "us-central1")

    key = (os.environ.get("GEMINI_API_KEY")
           or os.environ.get("GOOGLE_API_KEY", ""))
    if not key:
        raise RuntimeError(
            "visuals.providers includes 'veo' but neither visuals.veo.vertex."
            "project nor GEMINI_API_KEY is set — see config.yaml")
    return genai.Client(api_key=key)


def _aspect(cfg: dict[str, Any]) -> str:
    w = int(cfg["video"]["width"])
    h = int(cfg["video"]["height"])
    return "9:16" if h > w else "16:9"


def _references(settings: dict[str, Any]) -> list[Any]:
    """Photographs that pin the subject's identity, as Veo asset references.

    Three is the ceiling across Flow, the Gemini app and the API. More than
    one is worth having: a single photograph fixes a pose as much as it fixes
    an animal, and the model then reproduces the pose.
    """
    from google.genai import types

    root = Path(__file__).resolve().parent.parent
    refs = []
    for name in (settings.get("reference_images") or [])[:3]:
        path = Path(name)
        if not path.is_absolute():
            path = root / path
        if not path.exists():
            raise RuntimeError(f"visuals.veo.reference_images: no such file: {path}")
        refs.append(types.VideoGenerationReferenceImage(
            image=types.Image.from_file(location=str(path)),
            reference_type="ASSET",
        ))
    return refs


def _prompt(query: str, settings: dict[str, Any]) -> str:
    """The shot description Veo is given.

    The scripts' `visual_queries` are search terms written for stock
    libraries - three or four nouns. A generator wants a shot, so the style
    line carries the camera, the lens and the grade, and the query carries
    the subject.
    """
    style = (settings.get("style") or "").strip()
    return f"{query.strip()}. {style}".strip() if style else query.strip()


def render_clip(query: str, seconds: float, cfg: dict[str, Any], dest) -> Any:
    """Generate `seconds` of footage for `query` and write it to `dest`.

    Same contract as the drawn backends, so nothing upstream knows or cares
    which one produced the file.
    """
    from google.genai import types

    dest = Path(dest)
    settings = cfg["visuals"].get("veo") or {}

    # A quota or billing refusal will be the same answer for every shot, so
    # the first one retires the provider for the rest of the build rather
    # than asking again per shot.
    if cfg.get("_veo_off"):
        raise RuntimeError(cfg["_veo_off"])

    spent = cfg.setdefault("_veo_spent", {"clips": 0, "seconds": 0.0})
    cap = int(settings.get("max_clips_per_build", 20))
    if spent["clips"] >= cap:
        raise RuntimeError(
            f"visuals.veo.max_clips_per_build ({cap}) reached for this build")

    # Shots cut from the same scene share a query. Generating each one
    # separately pays twice for the same sentence and, worse, gets two
    # different takes of it - so a query generated once is reused.
    cache: dict[str, str] = cfg.setdefault("_veo_cache", {})
    if settings.get("reuse_by_query", True) and query in cache:
        shutil.copyfile(cache[query], dest)
        return dest

    client = _client(settings)
    want = max(4, min(int(settings.get("max_seconds", 8)),
                      int(round(seconds)) or 4))
    config = types.GenerateVideosConfig(
        aspect_ratio=_aspect(cfg),
        resolution=str(settings.get("resolution", "720p")),
        duration_seconds=want,
        number_of_videos=1,
        # "dont_allow" is rejected by the developer API ("currently not
        # supported"), so the setting is passed only when it is set to
        # something and omitted otherwise.
        person_generation=(settings.get("person_generation") or None),
        negative_prompt=(settings.get("negative_prompt") or None),
    )
    # `generate_audio` exists only on the Vertex/Enterprise path; passing it
    # with a plain developer API key is rejected outright. On this path Veo
    # decides for itself, and the track is discarded downstream anyway - the
    # narration and the music are mixed by render.py.
    if getattr(client, "vertexai", False):
        config.generate_audio = bool(settings.get("generate_audio", False))
    refs = _references(settings)
    if refs:
        config.reference_images = refs

    from google.genai import errors
    try:
        operation = client.models.generate_videos(
            model=str(settings.get("model", MODEL_DEFAULT)),
            prompt=_prompt(query, settings),
            config=config,
        )
    except errors.ClientError as exc:
        if exc.code in (401, 403, 429):
            cfg["_veo_off"] = f"veo off for this build: {exc.code} {exc.status}"
        raise
    for _ in range(POLL_LIMIT):
        if operation.done:
            break
        time.sleep(POLL_SECONDS)
        operation = client.operations.get(operation)
    if not operation.done:
        raise RuntimeError(f"veo: timed out after {POLL_LIMIT * POLL_SECONDS}s")

    error = getattr(operation, "error", None)
    if error:
        raise RuntimeError(f"veo: {error}")
    videos = getattr(operation.response, "generated_videos", None) or []
    if not videos:
        # Veo declines rather than fails when a prompt trips a filter, so an
        # empty response is a rejected prompt, not a broken request.
        raise RuntimeError(f"veo returned no video for {query!r} — the prompt "
                           f"may have been filtered")

    video = videos[0].video
    client.files.download(file=video)
    video.save(str(dest))
    spent["clips"] += 1
    spent["seconds"] += want
    cache[query] = str(dest)
    return dest
